const BASE_URL = 'https://api.frankfurter.app/latest';
const ADD_VALUE = 'ADD_VALUE';
const REMOVE_LAST_VALUE = 'REMOVE_LAST_VALUE';
const CHANGE_FROM_ON_TO_CURRENCY = 'CHANGE_FROM_ON_TO_CURRENCY';
const CHANGE_TO_ON_FROM_CURRENCY = 'CHANGE_TO_ON_FROM_CURRENCY';
const ADD_FROM_CURRENCY = 'ADD_FROM_CURRENCY';
const ADD_TO_CURRENCY = 'ADD_TO_CURRENCY';
const ADD_OPTIONS = 'ADD_OPTIONS';
const ADD_EXCHANGE_RATE = 'ADD_EXCHANGE_RATE';
const maxLength = 18;

export {
  BASE_URL,
  ADD_VALUE,
  REMOVE_LAST_VALUE,
  CHANGE_FROM_ON_TO_CURRENCY,
  CHANGE_TO_ON_FROM_CURRENCY,
  ADD_FROM_CURRENCY,
  ADD_TO_CURRENCY,
  ADD_OPTIONS,
  ADD_EXCHANGE_RATE,
  maxLength
}
